import type {Metadata} from "next";
import "../globals.css";
import {AppHeader} from "@/src/components/AppHeader";
import {AppFooter} from "@/src/components/AppFooter";
import {ModalProvider} from "@/src/contexts/ModalContext";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en" className="overflow-x-hidden">
            <body className="bg-background font-body antialiased relative overflow-x-hidden">
                <div className="grid-container mb-3">
                    <span className="border-r border-neutral-200"></span>

                    <ModalProvider>
                        <AppHeader />
                    </ModalProvider>

                    <span className="border-l border-neutral-200"></span>
                </div>

                {children}

                <AppFooter />
            </body>
        </html>
    );
}
