import type {Metadata} from "next";
import "@/app/globals.css";
import {BlobSuccessLeft} from "@/src/components/BlobSuccessLeft";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function SuccessLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
            <body className="bg-background font-body antialiased relative overflow-hidden h-screen grid place-items-center">
                {children}

                <BlobSuccessLeft className="absolute left-0 top-1/3" />
            </body>
        </html>
    );
}
